#!/usr/bin/env python
import os
import sys
if not os.path.exists("test-install"):
    print "Please run 'make test-install' first."
    sys.exit(0)
sys.path = ["test-install"]+sys.path
import neuroimaging.tests

if len(sys.argv) < 2: neuroimaging.tests.test_all()
else: neuroimaging.tests.test_package(sys.argv[1])
