# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

parameters:
  # defaults for any parameters that are not specified
  name: ''
  vmImage: ''


jobs:

- job: ${{ parameters.name }}Test
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ if eq(parameters.name, 'Linux') }}:
        python_314t_latest:
          python.version: '3.14'
          python.architecture: 'x64-freethreaded'
        python_312_latest:
          python.version: '3.12'
          python.architecture: 'x64'
          coverage: true
          lint: true
        python_311_latest:
          python.version: '3.11'
          python.architecture: 'x64'
          lint: true
          CYTHON_VERSION: 3.0.12
          coverage: true
        python_311_wheel:
          python.version: '3.11'
          python.architecture: 'x64'
          test.install: true
        python_312_sdist:
          python.version: '3.12'
          python.architecture: 'x64'
          test.install: true
          TEST_SDIST: true
        python_39:
          python.version: '3.9'
          python.architecture: 'x64'
          USE_MATPLOTLIB_VERSION: false
          USE_CVXOPT: false
          SCIPY_VERSION: 1.8.1
          PANDAS_VERSION: 1.5.3
          NUMPY_VERSION: 1.23.5
          CYTHON_VERSION: 3.0.10
          coverage: true
          lint: true
        python_310_legacy_blas:
          python.version: '3.10'
          python.architecture: 'x64'
          use.conda: true
          coverage: true
          NUMPY_VERSION: 2.0.0
          PANDAS_VERSION: 2.2.2
          SCIPY_VERSION: 1.13.0
          CYTHON_VERSION: 3.0.12
          BLAS: "nomkl blas=*=openblas"
          PYTEST_OPTIONS: ''
          lint: true
        python310_numpy124:
          python.version: '3.10'
          python.architecture: 'x64'
          NUMPY_VERSION: 1.24.4
          SCIPY_VERSION: 1.9.3
          PANDAS_VERSION: 1.5.3
          MATPLOTLIB_VERSION: 3.6.0
        python_313_copy_on_write:
          python.version: '3.13'
          python.architecture: 'x64'
          SM_TEST_COPY_ON_WRITE: 1
          lint: true
        python_312_pre:
          python.version: '3.12'
          python.architecture: 'x64'
          pip.pre: true
        python_312_formulaic:
          python.version: '3.12'
          python.architecture: 'x64'
          SM_FORMULA_ENGINE: "formulaic"
        python_312_no_patsy:
          python.version: '3.12'
          python.architecture: 'x64'
          PIP_UNINSTALL: "patsy"
        python_312_no_formulaic:
          python.version: '3.12'
          python.architecture: 'x64'
          PIP_UNINSTALL: "formulaic"
      ${{ if eq(parameters.name, 'macOS') }}:
        python310_macos_latest:
          python.version: '3.10'
          python.architecture: 'x64'
        python311_macos_latest:
          python.version: '3.11'
          python.architecture: 'x64'
        python312_macos_latest:
          python.version: '3.12'
          python.architecture: 'x64'
        python313_macos_latest_install:
          python.version: '3.13'
          python.architecture: 'x64'
          test.install: true
    maxParallel: 10

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'
    displayName: 'Use Python $(python.version) $(python.architecture)'

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      echo "##vso[task.prependpath]$CONDA/envs/statsmodels-test"
      echo "##vso[task.prependpath]$CONDA/envs/statsmodels-test/condabin"
      echo "##vso[task.prependpath]$CONDA/envs/statsmodels-test/bin"
    displayName: 'Add conda and env to PATH'
    condition: eq(variables['use.conda'], 'true')

  - script: |
      source tools/ci/azure/install-posix.sh
    displayName: 'Install dependencies'

  - script: ./lint.sh
    displayName: 'Check style'
    condition: eq(variables['lint'], 'true')

  - script: |
      echo "Installing to site packages"
      if [[ $TEST_SDIST ]]; then
        python -m pip install --upgrade build
        python -m build . --sdist
        TAIL=".tar.gz"
      else
        python -m pip wheel . -w ./dist -v
        TAIL=".whl"
      fi
      ls -t dist/statsmodels*${TAIL}
      PKG_NAME=$(ls -t dist/statsmodels*${TAIL})
      python -m pip install ./${PKG_NAME}
    displayName: 'Install statsmodels (site-packages)'
    condition: eq(variables['test.install'], 'true')

  - script: |
       python -m pip install -vv --no-build-isolation --upgrade-strategy only-if-needed --config-settings=editable-verbose=true --editable .
    displayName: 'Install statsmodels (editable)'
    condition: ne(variables['test.install'], 'true')

  - script: |
      if [[ -n ${PIP_UNINSTALL} ]]; then
        python -m pip uninstall ${PIP_UNINSTALL} -y
      fi
    displayName: 'Optionally Uninstall Packages'
    condition: eq(variables['use.conda'], 'true')

  - script: python -m pip list
    displayName: 'List Configuration (PyPI)'
    condition: ne(variables['use.conda'], 'true')

  - script: |
      source activate statsmodels-test
      conda list
    displayName: 'List Configuration (conda)'
    condition: eq(variables['use.conda'], 'true')

  - script: |
      echo "Testing site packages"
      mkdir test_run_dir
      pushd test_run_dir
      python -c "import statsmodels; statsmodels.test(['-n', 'auto', '--junitxml=../junit/test-results.xml', '--skip-examples', '--dist', 'loadscope', '--durations=25'], exit=True)"
      LAST_EXIT_CODE=$?
      echo "Status code: ${LAST_EXIT_CODE}"
      exit ${LAST_EXIT_CODE}
      popd
    displayName: 'Run tests (site-packages)'
    condition: eq(variables['test.install'], 'true')

  - script: |
      echo "Testing editable install"
      if [[ ${COVERAGE} == "true" ]]; then
        export COVERAGE_OPTS="--cov-config .coveragerc --cov=statsmodels --cov-report xml:coverage.xml --cov-report term"
      fi
      echo pytest -m "${PYTEST_PATTERN}" --skip-examples --junitxml=junit/test-results.xml -n auto --dist loadscope --durations=25 ${COVERAGE_OPTS} statsmodels
      pytest -m "${PYTEST_PATTERN}" --skip-examples --junitxml=junit/test-results.xml -n auto --dist loadscope --durations=25 ${COVERAGE_OPTS} statsmodels
    displayName: 'Run tests (editable)'
    condition: and(ne(variables['test.install'], 'true'), ne(variables['pip.pre'], 'true'))

  - script: |
      echo "Testing pip-pre"
      if [[ ${COVERAGE} == "true" ]]; then
        export COVERAGE_OPTS="--cov-config .coveragerc --cov=statsmodels --cov-report xml:coverage.xml --cov-report term"
      fi
      echo pytest -m "${PYTEST_PATTERN}" --skip-examples --junitxml=junit/test-results.xml -n auto --dist loadscope --durations=25 ${COVERAGE_OPTS} statsmodels
      pytest -m "${PYTEST_PATTERN}" --skip-examples --junitxml=junit/test-results.xml -n auto --dist loadscope --durations=25 ${COVERAGE_OPTS} statsmodels
    displayName: 'Run tests (pip pre)'
    condition: and(ne(variables['test.install'], 'true'), eq(variables['pip.pre'], 'true'))
    continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    condition: and(eq(variables['coverage'], 'true'), ne(variables['test.install'], 'true'))

  - bash: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov
      chmod +x codecov
      ./codecov
    displayName: 'CodeCov upload'
    condition: and(eq(variables['coverage'], 'true'), ne(variables['test.install'], 'true'))
    continueOnError: true
