#!/bin/env python
import os
os.system("python -c 'from neuroimaging import test; test()' &> ntest.pre")
os.system('grep test_ ntest.pre | grep " ok" > ntest.final')
os.system("python -c 'from neuroimaging import testall; testall()' &> testall.pre")
os.system('grep test_ testall.pre | grep " ok" > testall.final')

def open_test_set(filename):
    return set([l.split(' ',1)[0]+"::"+(l.split()[1]).split('.')[-3] \
      for l in open(filename).readlines()])

def print_test_set(tset):
    tlist= list(tset)
    tlist.sort()
    for i,t in enumerate(tlist): print "%d %s"%(i,t)

test = open_test_set('ntest.final')
testall = open_test_set('testall.final')

print "%d total tests"%len(test.union(testall))
print "%d test tests"%len(test)
print "%d testall tests"%len(testall)
print "%d found by test but not by testall"%len(test-testall)
print_test_set(test-testall)
print "%d found by testall but not by test"%len(testall-test)
print_test_set(testall-test)
print "%d found by both"%len(test.intersection(testall))
