name: pip_install
on: [pull_request, push]
jobs:
  pip_install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    # [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']  # ['3.7', '3.8', '3.9', '3.10', '3.11', 'pypy3.9']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install statsmodels
